openapi: 3.0.0
info:
  title: Blogs API
  version: 1.0.0
  description: Blogs API documentation

tags:
  - name: Blogs
    description: API for managing blogs
  - name: Posts
    description: API for managing posts
  - name: Testing
    description: API for clearing the database